version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'kanas_dev'
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run app
    environment:
      DATABASE_URL: postgres://postgres@postgres/kanas_dev
